algorithm_kwargs:
  batch_size: 1
  eval_freq: 2
  num_epochs: 64
  start_epoch: 18
amp: false
dataset_kwargs:
  batch_size: 1
  crop_size: 512
  dataset: ade20k
  image_size: 512
  normalization: deit
  num_workers: 10
  re_mode: pixel
  split: train
debug: false
inference_kwargs:
  im_size: 512
  window_size: 512
  window_stride: 512
net_kwargs:
  backbone: vit_deit_base_distilled_patch16_384
  d_model: 768
  decoder:
    drop_path_rate: 0.0
    dropout: 0.1
    n_cls: 150
    n_layers: 2
    name: mask_transformer_l2.u1.d768
  distilled: true
  drop_path_rate: 0.1
  dropout: 0.0
  image_size: !!python/tuple
  - 512
  - 512
  mlp_ratio: 4
  n_cls: 150
  n_heads: 12
  n_layers: 12
  normalization: deit
  patch_size: 16
optimizer_kwargs:
  clip_grad: null
  epochs: 64
  iter_max: 161728
  iter_warmup: 0.0
  lr: 0.001
  min_lr: 1.0e-05
  momentum: 0.9
  opt: sgd
  poly_power: 0.9
  poly_step_size: 1
  sched: polynomial
  weight_decay: 0.0
resume: true
seed: 3
version: normal
world_batch_size: 8